module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  blog: 0
  breakpoint: 0
  cache_alter: 0
  catalog: 0
  ckeditor: 0
  cmlstarter: 0
  cmlstarter_demo: 0
  colorbox: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_price: 0
  commerce_product: 0
  commerce_shipping: 0
  commerce_store: 0
  config: 0
  contact: 0
  contact_ajax: 0
  contact_block: 0
  contact_mail: 0
  contact_storage: 0
  contextual: 0
  cshs: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  f_callback: 0
  f_contact: 0
  f_order: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  image: 0
  image_effects: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpmail_alter: 0
  physical: 0
  profile: 0
  quickedit: 0
  responsive_image: 0
  service: 0
  shs: 0
  social_api: 0
  social_auth: 0
  social_auth_facebook: 0
  state_machine: 0
  synajax: 0
  synapse: 0
  syncabinet: 0
  syncart: 0
  synfilters: 0
  synhelper: 0
  synlanding: 0
  synmap: 0
  synorders: 0
  synpay: 0
  synsearch: 0
  synship: 0
  syntheme: 0
  synusers: 0
  syspage: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  xframe_allow_webvisor: 0
  yaml_editor: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  tvi: 15
  synmini: 1000
theme:
  seven: 0
  stable: 0
  classy: 0
  bootbase: 0
  adaptive: 0
  claro: 0
profile: synmini
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: ru
