yamap-name: ''
yamap-enable: enable_contact
yamap-path: /node/1
yamap-attach: .footer
map-latitude: '39.858191'
map-longitude: '59.214189'
map-zoom: '16'
map-offset_x: ''
map-offset_y: ''
langcode: ru
yamap-method: before
_core:
  default_config_hash: mrFtsXUH3l5cQo8IrckdfIdlEKvF0HL6TDAnekzepqc
map-apikey: d73c51ac-cd05-4cfc-a526-1beeb92228f3
