sberbank_active: '1'
sberbank_test_mode: '1'
sberbank_test_login: T350501308607-api
sberbank_test_token: T350501308607
sberbank_live_login: ''
sberbank_live_token: ''
sberbank_description: ''
robokassa_active: '0'
robokassa_test_mode: '0'
robokassa_test_login: ''
robokassa_test_token: ''
robokassa_live_login: ''
robokassa_live_token: ''
robokassa_description: ''
yookassa_active: '0'
yookassa_test_mode: '0'
yookassa_test_login: ''
yookassa_test_token: ''
yookassa_live_login: ''
yookassa_live_token: ''
yookassa_description: ''
tinkoff_active: '0'
tinkoff_test_mode: '0'
tinkoff_test_login: ''
tinkoff_test_token: ''
tinkoff_live_login: ''
tinkoff_live_token: ''
tinkoff_description: ''
active: 0
