first_day: 1
timezone:
  user:
    configurable: false
    warn: false
    default: 0
  default: Europe/Moscow
langcode: ru
_core:
  default_config_hash: 1K4Ck5D9u5CuQX_Tex9WXkwCakIbL5YIuTxxQH1LnJk
country:
  default: ''
